// Java Package mygodroid is a proxy for talking to a Go program.
//
// File is generated by gobind. Do not edit.
package go.mygodroid;

import go.Seq;

public abstract class Mygodroid {
    private Mygodroid() {} // uninstantiable
    
    public static void ListeAndServe() {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        Seq.send(DESCRIPTOR, CALL_ListeAndServe, _in, _out);
    }
    
    public static void SayHelloGo(String txt) {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        _in.writeUTF16(txt);
        Seq.send(DESCRIPTOR, CALL_SayHelloGo, _in, _out);
    }
    
    public static void StoreImage(String tmpFile, String fileName) {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        _in.writeUTF16(tmpFile);
        _in.writeUTF16(fileName);
        Seq.send(DESCRIPTOR, CALL_StoreImage, _in, _out);
    }
    
    private static final int CALL_ListeAndServe = 1;
    private static final int CALL_SayHelloGo = 2;
    private static final int CALL_StoreImage = 3;
    private static final String DESCRIPTOR = "mygodroid";
}
